### ISSUE TITLE
travis integration

### ISSUE THREAD

**Issue by bianchimro** [onlinebooking/booking-engine#3]
we have test ... why not integrate Travis CI?

https://docs.travis-ci.com/user/getting-started/

**Comment by gffuma** [comment]
Ti rispondo in Italiano XD Comunque io non ho mai messo travis per un un organization stavo provando ma mi sa che serve il tuo "permesso" in quanto owner.

**Comment by gffuma** [comment]
Poi tra l'altro sarebbe fighissimo mettere il coverage sempre nel readme usando servizi tipo
https://codecov.io/
https://coveralls.io/
